
export const ROUTE_REGISTER="/register"
export const ROUTE_LOGIN="/login"
export const ROUTE_FORGOT_PASS="/password-reset"
export const ROUTE_CART="/checkout"
export const ROUTE_HOME="/"
export const ROUTE_CONTACT="/contact"
export const ROUTE_ABOUT="/about-us"
export const ROUTE_PROFILE="/profile"


export const BASE_URL="https://happy-mixed-gaura.glitch.me/ec2-3-16-214-18.us-east-2.compute.amazonaws.com:8080"
export const REGISTER_URL="user/create-user"
export const LOGIN_URL="login"
export const FORGOT_PASSWORD_URL="email/send-mail-recover"
export const RESET_PASSWORD_URL="email/change-password"
export const CHANGE_PASSWORD_URL="user/change-password"
export const COUPON_CLIENT_URL="coupon/valid-coupons"
export const PURCHAGE_URL="api/purchases"
export const PROFILE_URL_REST="user/profile"
export const UPDATE_INFO_USER_URL_REST="user/update"
export const UPDATE_PASS_USER_URL_REST="user/update/password"
export const REPORT_PURCHAGES_REST="api/purchases/account"