import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/ui/navbar";

const inter = Inter({ subsets: ["latin"] });
import { SessionProvider } from "../hooks/sessionContext";
import { HydrationProvider, Server, Client } from "react-hydration-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HydrationProvider>
          <Client>
            <SessionProvider>
              <Navbar />
              {children}
            </SessionProvider>
          </Client>
        </HydrationProvider>
      </body>
    </html>
  );
}
